apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: asiayo
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-do-db=your_database_name
    innodb_flush_log_at_trx_commit=1
    sync_binlog=1
    innodb_buffer_pool_size=256M
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
  namespace: asiayo
spec:
  serviceName: "mysql"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: asiayo
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
