apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: asiayo
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: asiayo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "600Mi"
              cpu: "1000m"
          volumeMounts:
            - name: nginx-config-data
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-data
          configMap:
            name: nginx-config
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: asiayo
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort